import {initial,act,legal,pipCount} from './engine.js';
import {zh} from './zh.js';
const $=id=>document.getElementById(id),tg=window.Telegram?.WebApp,initData=tg?.initData||'',live=!!initData;
const endpoint='https://wbyiwtrwtjmrwzpaalhk.supabase.co/functions/v1/hatzi-backgammon';
let payments={enabled:false,price:null,credits:1000},buying=false;
let isAdmin=false,adminOffset=0,customerPage=[],contact=null,contactLoaded=false;
const detected=tg?.initDataUnsafe?.user?.language_code||navigator.language||'en';
let lang=localStorage.getItem('bg-language')||(/^(he|iw)/.test(detected)?'he':/^zh/.test(detected)?'zh':'en'),game=null,busy=false,polling=false,selected=null,onHome=true,local=false,offset=0,active=null,leaderboard=null,profile=null,history=[],muted=localStorage.getItem('bg-muted')==='1',chatSending=false,lastMessages='';
const t=(he,english)=>lang==='he'?he:lang==='zh'?(zh[english]??english):english,die=()=>{let a=new Uint32Array(1);do{crypto.getRandomValues(a);}while(a[0]>=4294967292);return a[0]%6+1;};
function notice(message,error=false){$('notice').textContent=message||'';$('notice').hidden=!message;$('notice').className=error?'error':'';}
function label(id,he,english){$(id).textContent=t(he,english);}
function language(){document.documentElement.lang=lang==='zh'?'zh-Hans':lang;document.documentElement.dir=lang==='he'?'rtl':'ltr';$('language').value=lang;
  for(const [id,he,eng] of [['home','בית','Home'],['eyebrow','שש־בש. שחקנים אמיתיים.','BACKGAMMON. REAL PLAYERS.'],['title','המהלך הבא שלך.','Your next move.'],['intro','הזמן חבר או מצא יריב. הקוביות אקראיות, המהלכים שלך.','Invite a friend or find an opponent. Random dice. Your decisions.'],['ranked','מצא יריב · מדורג','Find opponent · Ranked'],['friend','הזמן חבר','Invite a friend'],['demo','התנסות מקומית לשניים','Local two-player demo'],['telegram','פתח בטלגרם','Open in Telegram'],['resume','המשך משחק','Resume game'],['roll','זרוק קוביות','Roll dice'],['invite','העתק הזמנה','Copy invitation'],['cancel','בטל המתנה','Cancel waiting'],['claim','בקש ניצחון בזמן','Claim timeout win'],['resign','פרוש','Resign'],['rankTitle','טבלת שחקנים','Player rankings'],['refresh','רענן','Refresh'],['eloTitle','דירוג Elo','Elo rating'],['monthTitle','החודש','This month'],['historyTitle','המשחקים האחרונים שלך','Your recent games'],['rulesTitle','איך משחקים?','How to play'],['footer','התנסות מקומית חינם · משחק מקוון דרך טלגרם','Free local demo · Online play through Telegram']])label(id,he,eng);
  label('rules','לחץ על אבן מודגשת ואז בחר יעד או מהלך. חובה להשתמש במספר הקוביות המרבי; אם אפשר להשתמש רק באחת, בחר בגבוהה. דאבל נותן ארבעה מהלכים. אבנים שבמרכז נכנסות לפני כל מהלך אחר. מוציאים אבנים רק כשכולן בבית. הראשון שמוציא 15 מנצח. 40 שניות ללא מהלך חוקי או זריקת קוביות גורמות להפסד טכני אוטומטי. משחקי חברים אינם מדורגים. מול אותו יריב נספר רק משחק מדורג אחד ב־24 שעות. הלוח החודשי סופר ניצחונות מדורגים לפי חודש UTC, עם Elo כשובר שוויון. אין פרס פעיל.','Select a highlighted checker, then a destination or move. Use as many dice as possible; if only one can be used, use the higher die. Doubles give four moves. Enter bar checkers first. Bear off only when all checkers are home. First to bear off 15 wins. No legal move or dice roll for 40 seconds causes an automatic technical loss. Friend games are unranked. Only one ranked result per opponent per 24 hours counts. Monthly standings count ranked wins by UTC month, with Elo as a tiebreaker. No active prize.');
  label('chatTitle','צ׳אט עם היריב','Chat with opponent');label('send','שלח','Send');$('chatInput').placeholder=t('כתוב הודעה…','Write a message…');lastMessages='';
  $('ranked').hidden=!live;$('friend').hidden=!live;$('telegram').hidden=live;renderLists();renderWallet();renderContact();render();
}
async function api(action,extra={}){const start=Date.now(),r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,initData,...extra}),signal:AbortSignal.timeout(15000)});const d=await r.json();if(d.serverNow)offset=d.serverNow-(start+Date.now())/2;if(!r.ok)throw Error(lang==='zh'?(zh[d.error]??d.error):d.error||t('החיבור נכשל','Connection failed'));return d;}
function setBusy(v){busy=v;for(const id of ['ranked','friend','ready','roll','resign','cancel','claim'])$(id).disabled=v;}
async function mutate(action,extra={}){
  if(busy)return;setBusy(true);notice('');selected=null;
  if(action==='roll')$('dice').classList.add('rolling');
  try{const started=Date.now();if(local){if(action==='resign'&&!confirm(t('לפרוש מהמשחק?','Resign this game?')))return;game.state=act(game.state,game.state.turn,{type:action,...extra},die);game.status=game.state.winner===null?'playing':'finished';game.version++;game.player=game.state.turn;game.legal=legal(game.state);game.pips=[pipCount(game.state,0),pipCount(game.state,1)];}
    else {const d=await api(action,{requestId:crypto.randomUUID(),...(game?{gameId:game.id,version:game.version}:{}),...extra});game=d.game;active=game;}
    if(action==='roll')await new Promise(r=>setTimeout(r,Math.max(0,650-(Date.now()-started))));onHome=false;render();
  }catch(e){notice(e.message,true);if(live&&!local)await refreshGame(true);}finally{$('dice').classList.remove('rolling');setBusy(false);render();}
}
function demo(){local=true;onHome=false;game={id:'local',version:1,status:'playing',mode:'friend',white:{name:t('שחקן לבן','White player'),rating:'—'},black:{name:t('שחקן שחור','Black player'),rating:'—'},state:initial(die)};game.player=game.state.turn;game.legal=legal(game.state);game.pips=[167,167];selected=null;notice(t('התנסות לשני אנשים באותו מכשיר. למשחק מרחוק פתחו את הבוט.','Local demo for two people on this device. Open Telegram to play remotely.'));render();}
const pointName=i=>i===-1?t('מרכז','Bar'):i===24?t('בחוץ','Off'):String(i+1);
function stone(color,count=1){const s=document.createElement('span');s.className='checker '+color;if(count>1)s.textContent=count;return s;}
function moveOptions(){return game?.legal??[];}
function choose(from){if(busy||game.status!=='playing')return;const destinations=moveOptions().filter(m=>m.from===selected&&m.to===from);if(destinations.length===1)return mutate('move',{from:selected,die:destinations[0].die});selected=selected===from?null:from;render();}
function point(i,bottom){const el=document.createElement('button');el.type='button';el.className='point'+(bottom?' bottom':'')+(i%2?' alt':'');const n=game.state.board[i];el.setAttribute('aria-label',`${t('נקודה','Point')} ${i+1}: ${Math.abs(n)} ${n>=0?t('לבנות','white'):t('שחורות','black')}`);const number=document.createElement('span');number.className='number';number.textContent=i+1;el.append(number);for(let k=0;k<Math.min(5,Math.abs(n));k++)el.append(stone(n>0?'white':'black',k===4?Math.abs(n)-4:1));if(moveOptions().some(m=>m.from===i))el.classList.add('legal');if(selected===i)el.classList.add('selected');if(moveOptions().some(m=>m.from===selected&&m.to===i))el.classList.add('destination');el.onclick=()=>choose(i);return el;}
function drawDice(){const wrap=$('dice');wrap.replaceChildren();if(game.status==='waiting')return;const s=game.state,list=s.dice?.[0]===s.dice?.[1]?[s.dice[0],s.dice[0],s.dice[0],s.dice[0]]:s.dice||[];const remaining=[...s.remaining];const layouts={1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]};for(const n of list){const d=document.createElement('div');d.className='die';const available=remaining.indexOf(n);if(available<0)d.classList.add('used');else remaining.splice(available,1);d.setAttribute('aria-label',t('קובייה ','Die ')+n);for(let i=0;i<9;i++){const p=document.createElement('span');if(layouts[n].includes(i))p.className='pip';d.append(p);}wrap.append(d);}}
function render(){
  $('lobby').hidden=!onHome;$('gameArea').hidden=onHome||!game;$('resume').hidden=!active||!['waiting','playing'].includes(active.status);if(onHome||!game)return;
  renderChat();const s=game.state,playing=game.status==='playing',mine=local||s.turn===game.player,waiting=game.status==='waiting',ended=game.status==='finished';
  $('whiteName').textContent=game.white?.name??t('לבן','White');$('blackName').textContent=game.black?.name??t('ממתין ליריב','Waiting for opponent');$('whiteRating').textContent=game.white?.rating??1200;$('blackRating').textContent=game.black?.rating??'';
  $('whitePips').textContent=(game.pips?.[0]??167)+' '+t('צעדים','pips');$('blackPips').textContent=(game.pips?.[1]??167)+' '+t('צעדים','pips');
  $('board').replaceChildren();for(const bottom of [false,true]){const indices=bottom?Array.from({length:12},(_,i)=>11-i):Array.from({length:12},(_,i)=>12+i);indices.forEach((i,k)=>{if(k===6){const bar=document.createElement('button');bar.className='bar';bar.setAttribute('aria-label',t('אבנים במרכז','Bar checkers'));bar.onclick=()=>choose(-1);if(moveOptions().some(m=>m.from===-1))bar.classList.add('legal');const barPlayer=bottom?0:1;if(s.bar[barPlayer])bar.append(stone(barPlayer===0?'white':'black',s.bar[barPlayer]));$('board').append(bar);}$('board').append(point(i,bottom));});}
  for(const [id,p] of [['whiteOff',0],['blackOff',1]]){$(id).textContent=t(p===0?'לבן בחוץ: ':'שחור בחוץ: ',p===0?'White off: ':'Black off: ')+s.off[p]+'/15';$(id).classList.toggle('destination',s.turn===p&&moveOptions().some(m=>m.from===selected&&m.to===24));$(id).onclick=()=>{const choices=moveOptions().filter(m=>m.from===selected&&m.to===24);if(s.turn===p&&choices.length===1)mutate('move',{from:selected,die:choices[0].die});};}
  const color=t(s.turn===0?'לבן':'שחור',s.turn===0?'White':'Black');
  $('turnText').textContent=waiting?t('ממתינים לשחקן אמיתי…','Waiting for a real opponent…'):ended?(s.winner===0?game.white?.name:game.black?.name)+' '+t('ניצח!','wins!'):game.status==='cancelled'?t('ההמתנה בוטלה','Waiting cancelled'):local?color+' · '+t('תורך','your turn'):mine?t('תורך · ','Your turn · ')+color:t('תור היריב · ','Opponent’s turn · ')+color;
  $('mode').textContent=local?t('מקומי','LOCAL'):game.mode==='ranked'?t('מדורג','RANKED'):t('חברים · ללא דירוג','FRIENDLY');
  $('roll').hidden=!playing||!mine||s.phase!=='roll';$('roll').disabled=busy;$('resign').hidden=!playing;$('invite').hidden=!waiting||!!game.black||game.mode!=='friend';$('cancel').hidden=!waiting;$('claim').hidden=true;
  $('ready').hidden=!waiting||!game.black;label('ready','אני מוכן · כוכב משחק אחד','I’m ready · 1 game star');if(!payments.enabled)label('ready','אני מוכן','I’m ready');
  if(waiting&&game.black){$('turnText').textContent=t('שני השחקנים צריכים לאשר מוכנות','Both players must confirm readiness');label('hint','המשחק והחיוב יתחילו רק לאחר אישור שני השחקנים.','The game and charge start only after both players confirm.');}
  $('moves').replaceChildren();if(selected!==null)for(const m of moveOptions().filter(m=>m.from===selected)){const b=document.createElement('button');b.textContent=`${pointName(m.from)} → ${pointName(m.to)} · ⚄ ${m.die}`;b.onclick=()=>mutate('move',{from:m.from,die:m.die});b.disabled=busy;$('moves').append(b);}
  $('hint').textContent=waiting?(game.black?t('המשחק והחיוב יתחילו רק לאחר אישור שני השחקנים.','The game and charge start only after both players confirm.'):game.mode==='friend'?t('העתק את ההזמנה ושלח לחבר.','Copy the invitation and send it to a friend.'):t('המשחק יתחיל כאשר שחקן אחר יצטרף לחיפוש.','The game starts when another player joins matchmaking.')):ended?(local?t('ההתנסות הסתיימה. התוצאה אינה נשמרת בדירוג.','Demo finished. This result is not ranked.'):t('התוצאה נשמרה. חזור לבית למשחק נוסף.','Result saved. Return home for another game.')):mine&&s.phase==='move'?t('בחר אבן מודגשת, ואז יעד או מהלך.','Choose a highlighted checker, then a destination or move.'):t('40 שניות ללא תגובה גורמות להפסד טכני.','40 seconds of inactivity causes a technical loss.');drawDice();clock();
}
function clock(){if(!game||onHome)return;const left=Date.parse(game.deadline)-(Date.now()+offset);$('turnClock').textContent=local?t('מקומי','LOCAL'):game.status!=='playing'?'':Math.max(0,Math.ceil(left/1000))+'s';$('claim').hidden=true;if(game.status==='waiting'&&game.black){const stamp=game.state[game.player===0?'ready0':'ready1']??0;const confirmed=Date.now()+offset-stamp<30000;$('ready').disabled=busy||confirmed;if(confirmed)label('ready','מוכן · ממתין לאישור היריב','Ready · waiting for opponent');else label('ready',payments.enabled?'אני מוכן · כוכב משחק אחד':'אני מוכן',payments.enabled?'I’m ready · 1 game star':'I’m ready');}}
function renderLists(){
  $('profile').textContent=profile?`${t('הדירוג שלך','Your rating')}: ${profile.rating} · ${profile.wins} ${t('ניצחונות','wins')} · ${profile.losses} ${t('הפסדים','losses')}`:'';
  for(const id of ['ratings','monthly']){$(id).replaceChildren();const rows=leaderboard?.[id]??[];if(!rows.length){const li=document.createElement('li');li.textContent=t('משחקים מדורגים שהושלמו יופיעו כאן.','Completed ranked games will appear here.');$(id).append(li);}for(const p of rows){const li=document.createElement('li');li.textContent=id==='ratings'?`${p.name} · ${p.rating}`:`${p.name} · ${p.wins} ${t('ניצחונות','wins')}`;$(id).append(li);}}
  $('history').replaceChildren();for(const r of history){const item=document.createElement('div');item.textContent=(r.won?t('ניצחון','Win'):t('הפסד','Loss'))+' · '+new Date(r.created_at).toLocaleDateString(lang)+' · '+(r.rated?(r.won?'+':'−')+r.delta+' Elo':t('ללא שינוי דירוג','Unrated'));$('history').append(item);}
  if(leaderboard?.month)$('monthTitle').textContent=t('החודש · ','This month · ')+leaderboard.month;
}
async function home(){onHome=true;selected=null;notice('');render();if(!live)return;try{const d=await api('home');active=d.game;profile=d.profile;payments=d.payments;leaderboard=d.leaderboard;history=d.history;isAdmin=d.isAdmin;contact=d.contact;if(!contactLoaded){$('email').value=contact?.email??'';$('updatesOpt').checked=contact?.updates_opt_in===true;$('eventsOpt').checked=contact?.events_opt_in===true;contactLoaded=true;}if(!localStorage.getItem('bg-language')&&profile.language){lang=profile.language;language();}renderLists();renderWallet();renderContact();render();}catch(e){notice(e.message,true);}}
function renderContact(){
  $('contactPanel').hidden=!live;$('adminToggle').hidden=!isAdmin;label('adminToggle','ניהול','Admin');label('contactTitle','עדכונים ומפגשי משחק · לבחירתך','Updates and game meetups · Optional');label('contactInfo','אפשר לשחק בלי למסור אימייל. HATZI ישתמש בכתובת רק למטרות שתסמן. ניתן לבטל כאן בכל עת.','You can play without providing email. HATZI will use it only for the purposes you select. You can withdraw consent here at any time.');label('updatesLabel','אני מסכים לקבל מ־HATZI באימייל מידע על שדרוגים והצעות','I agree to receive HATZI upgrade news and offers by email');label('eventsLabel','אני מסכים לקבל מ־HATZI הזמנות למפגשי משחק באימייל','I agree to receive HATZI game meetup invitations by email');label('saveContact','שמור העדפות','Save preferences');label('adminTitle','ניהול לקוחות','Customer management');label('adminRefresh','רענן','Refresh');label('adminPrevious','קודם','Previous');label('adminNext','הבא','Next');label('exportCustomers','ייצוא העמוד ל־CSV','Export page as CSV');label('adminNote','כתובות אימייל חדשות מסומנות כלא מאומתות. מערכת שליחת אימייל ואימות כתובות טרם חוברה; אין לשלוח דיוור לפני אימות והסכמה מתאימה.','New email addresses are unverified. Email delivery and address verification are not connected yet; verify addresses and the relevant consent before mailing.');
}
$('contactForm').onsubmit=async e=>{e.preventDefault();$('saveContact').disabled=true;try{await api('contact',{email:$('email').value,updates:$('updatesOpt').checked,events:$('eventsOpt').checked});$('contactStatus').textContent=t('ההעדפות נשמרו. אפשר לשנות או לבטל כאן בכל עת.','Preferences saved. You can change or withdraw them here at any time.');}catch(e){$('contactStatus').textContent=e.message;}finally{$('saveContact').disabled=false;}};
async function loadCustomers(){if(!isAdmin)return;try{const d=await api('customers',{offset:adminOffset});customerPage=d.customers;$('adminSummary').textContent=`${t('לקוחות','Customers')}: ${d.total} · ${t('פעילים ב־30 יום','Active in 30 days')}: ${d.active30d} · ${d.paidStars} Telegram Stars`;$('customers').replaceChildren();for(const p of customerPage){const box=document.createElement('article');box.className='customer';const heading=document.createElement('strong');heading.textContent=p.name+' · '+p.user_id;const info=document.createElement('p');info.textContent=`${p.language} · Elo ${p.rating} · ${p.games} ${t('משחקים','games')} · ${p.credits} ${t('כוכבי משחק','game stars')} · ${p.paid_stars} Telegram Stars`;const email=document.createElement('p');email.textContent=(p.email||'—')+' · '+t('עדכונים','Updates')+': '+!!p.updates_opt_in+' · '+t('מפגשים','Meetups')+': '+!!p.events_opt_in+' · '+t('מאומת','Verified')+': '+!!p.email_verified;const dates=document.createElement('small');dates.textContent=t('הצטרפות: ','Joined: ')+new Date(p.created_at).toLocaleString(lang)+' · '+t('נראה לאחרונה: ','Last seen: ')+new Date(p.last_seen).toLocaleString(lang);box.append(heading,info,email,dates);$('customers').append(box);}$('adminPrevious').disabled=adminOffset===0;$('adminNext').disabled=adminOffset+100>=d.total;}catch(e){notice(e.message,true);}}
$('adminToggle').onclick=()=>{$('adminPanel').hidden=!$('adminPanel').hidden;if(!$('adminPanel').hidden)loadCustomers();};$('adminRefresh').onclick=loadCustomers;$('adminPrevious').onclick=()=>{adminOffset=Math.max(0,adminOffset-100);loadCustomers();};$('adminNext').onclick=()=>{adminOffset+=100;loadCustomers();};
$('exportCustomers').onclick=()=>{if(!isAdmin||!customerPage.length)return;const keys=['user_id','name','language','rating','wins','losses','games','credits','paid_stars','email','updates_opt_in','events_opt_in','email_verified','created_at','last_seen'];const safe=x=>'"'+String(x??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const csv='\uFEFF'+[keys.join(','),...customerPage.map(p=>keys.map(k=>safe(p[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='hatzi-customers-'+adminOffset+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function renderWallet(){
  $('wallet').hidden=!live||!payments.enabled;label('walletTitle','כוכבי המשחק שלך','Your game stars');$('balance').textContent=(profile?.credits??0)+' '+t('כוכבי משחק','game stars');$('packText').textContent=`1,000 ${t('כוכבי משחק','game stars')} = ${payments.price??'—'} Telegram Stars`;label('acceptLabel','קראתי ואני מסכים לתנאי השימוש','I have read and accept the usage terms');label('termsLink','תנאי שימוש','Terms');label('buy','רכוש 1,000 כוכבי משחק','Buy 1,000 game stars');label('walletHelp','כל שחקן משלם כוכב משחק אחד בתחילת משחק. אין פדיון או העברה. המתנה וביטול לפני התחלה אינם מחויבים.','Each player spends 1 game star when a game starts. No redemption or transfers. Waiting and cancellation before start are free.');$('buy').disabled=buying||!$('acceptTerms').checked;if(payments.enabled)label('footer','כוכבי משחק לשימוש בלבד · אין הימורים או פרס פעיל','Game credits for play only · No wagering or active prizes');
}
$('acceptTerms').onchange=renderWallet;
$('buy').onclick=async()=>{if(buying||!$('acceptTerms').checked)return;buying=true;renderWallet();try{const d=await api('invoice',{requestId:crypto.randomUUID(),termsAccepted:true,termsVersion:'2026-09-20-v1'});tg.openInvoice(d.url,async status=>{buying=false;renderWallet();if(status==='paid'){await home();notice(t('התשלום התקבל. היתרה מתעדכנת לאחר אישור טלגרם.','Payment received. Balance updates after Telegram confirmation.'));setTimeout(()=>home(),2000);}else if(status==='failed')notice(t('התשלום לא הושלם. אפשר לנסות שוב.','Payment was not completed. Please try again.'),true);});}catch(e){buying=false;renderWallet();notice(e.message,true);}};
$('ready').onclick=()=>mutate('ready');
async function refreshGame(force=false){if(!live||local||!game||(!force&&(onHome||busy||polling||document.hidden)))return;polling=true;try{const d=await api('state',{gameId:game.id});if(d.game){const changed=d.game.version!==game.version;game=d.game;active=game;if(changed){selected=null;render();}else renderChat();}$('sync').textContent=t('מחובר · מצב המשחק נשמר בשרת','Connected · Game saved on server');}catch(e){$('sync').textContent=t('מתחבר מחדש…','Reconnecting…');}finally{polling=false;}}
function renderChat(){if(!game)return;label('mute',muted?'בטל השתקה':'השתק',muted?'Unmute':'Mute');const enabled=!local&&!!game.black&&['playing','finished'].includes(game.status);$('chatForm').hidden=!enabled||muted;$('chatHelp').textContent=local?t('להתנסות המקומית אין צ׳אט מקוון.','Local demo has no online chat.'):muted?t('הצ׳אט מושתק במכשיר הזה.','Chat is muted on this device.'):!enabled?t('הצ׳אט ייפתח כשהשחקן השני יצטרף.','Chat opens when a second player joins.'):'';const messages=muted?[]:game.messages??[],key=JSON.stringify(messages)+lang+muted;if(key===lastMessages)return;lastMessages=key;const list=$('messages'),nearBottom=list.scrollHeight-list.scrollTop-list.clientHeight<50;list.replaceChildren();for(const m of messages){const box=document.createElement('div');box.className='chat-message'+(m.own?' own':'');const name=document.createElement('strong');name.textContent=m.own?t('אתה','You'):t('היריב','Opponent');const body=document.createElement('p');body.textContent=m.body;body.dir='auto';box.append(name,body);list.append(box);}if(nearBottom)list.scrollTop=list.scrollHeight;}
$('mute').onclick=()=>{muted=!muted;localStorage.setItem('bg-muted',muted?'1':'0');renderChat();};
$('chatForm').onsubmit=async e=>{e.preventDefault();const body=$('chatInput').value.trim();if(!body||chatSending||!game||local)return;chatSending=true;$('send').disabled=true;try{await api('chat',{gameId:game.id,requestId:crypto.randomUUID(),body});$('chatInput').value='';await refreshGame(true);}catch{notice(t('ההודעה לא נשלחה. המתן מעט ונסה שוב.','Message could not be sent. Please wait and retry.'),true);}finally{chatSending=false;$('send').disabled=false;}};
$('language').onchange=async()=>{lang=$('language').value;localStorage.setItem('bg-language',lang);language();if(live)try{await api('preferences',{language:lang});}catch(e){notice(e.message,true);}};$('home').onclick=home;$('refresh').onclick=home;$('ranked').onclick=()=>{local=false;game=null;mutate('ranked');};$('friend').onclick=()=>{local=false;game=null;mutate('friend');};$('demo').onclick=demo;$('resume').onclick=()=>{local=false;game=active;onHome=false;render();refreshGame();};$('roll').onclick=()=>mutate('roll');$('cancel').onclick=()=>mutate('cancel');$('claim').onclick=()=>mutate('claim');$('resign').onclick=()=>{if(local||confirm(t('לפרוש? היריב ינצח.','Resign? Your opponent will win.')))mutate('resign');};$('invite').onclick=async()=>{const link='https://t.me/HatziBackgammonBot?start=g_'+game.id;try{await navigator.clipboard.writeText(link);notice(t('ההזמנה הועתקה. אפשר לשלוח לחבר.','Invitation copied. Send it to a friend.'));}catch{notice(link);}};
if(live){tg.ready();tg.expand();try{tg.setHeaderColor('#122b29');tg.setBackgroundColor('#122b29');}catch{}}
language();const invitation=new URLSearchParams(location.search).get('game');if(live&&invitation){await home();mutate('join',{gameId:invitation});}else home();
setInterval(refreshGame,2000);setInterval(clock,500);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshGame();});
